[start]
cmd = "gunicorn run:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120"

[phases.setup]
nixPkgs = ["python312", "pkg-config", "mysql80"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[variables]
PYTHONPATH = "/app"
